// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxbyjvagvrdenkvazcou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4YnlqdmFndnJkZW5rdmF6Y291Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNTA0NDAsImV4cCI6MjA2MTkyNjQ0MH0.PTXiL5bzjtoxSBtr2moeX55NHRhOKvLYZesLNMlfURg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);